[package]
name = "opengl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "*"
sdl2 = {version = "0.36.0", features = ["bundled"]}
sdl2-sys = "0.36.0"